### ISSUE TITLE
CVV2 Reply Not being picked up in CardResponse

### ISSUE THREAD

**Issue by jain-chinmay** [Nuvei/nuvei-server-java#62]
Hi,

I am using SafeCharge Java wrapper to integrate Card Payments. However, there seems to be an issue with getting the CVV2 Response.

`public class CardResponse {

    private ApiExternalToken externalToken;
    private String ccCardNumber;
    private String bin;
    private String lastFourDigits;
    private String ccExpMonth;
    private String ccExpYear;
    private String acquirerId;
    private String cvv2Replay;
    private String avsCode;
    private String ccTempToken;
    private String isVerified;
    private ThreeDResponse threeD;
}`

The field **cvv2Replay** is null. In the docs, the field is named as [cvv2Reply](https://www.safecharge.com/docs/API/main/indexMain_v1_0.html?json#payment).

Could anyone look into this?

**Comment by VKNikov** [comment]
Thanks. It should be fixed now.
