### ISSUE TITLE
Issue: SDK restricted 2 max characters, but documentation do allow 3 characters

### ISSUE THREAD

**Issue by shiuh-yaw** [Nuvei/nuvei-server-java#77]
https://docs.nuvei.com/documentation/additional-links/country-and-currency-codes/#Australia

https://github.com/Nuvei/nuvei-server-java/blob/96f9b001db456c20a563f956f943620e22d8e0e0/src/main/java/com/safecharge/model/UserAddress.java#L66

**Comment by radtonev** [comment]
Thank you. We will solve this ASAP with new release.
